import { readFile, writeFile } from 'node:fs/promises';

const factoryUrl = new URL('./factory.js', import.meta.url);
const outputUrl = new URL('./iife.js', import.meta.url);

let source = await readFile(factoryUrl, 'utf8');

source = source.replace(
    /^export\s+function\s+createRemoteBase\s*\(\)\s*\{/m,
    'function createRemoteBase() {',
);

if (source.includes('export ')) {
    throw new Error('Unexpected ESM export remained in remote-base factory.');
}

const output = `// Generated by build-iife.mjs. Do not edit directly.\n` +
    `// Evaluating this file returns the remoteBase callable.\n\n` +
    source.trim() +
    `\n\ncreateRemoteBase();\n`;

await writeFile(outputUrl, output);
