export { createRemoteBase, remoteBase } from './lib/class.ts';
export type {
    AirtableRecordFields,
    AirtableRecordStrings,
    DeferredRemoteTable,
    DeleteInput,
    DeletedRecord,
    RemoteBase,
    RemoteBaseCallable,
    RemoteBaseConfig,
    RemoteBaseHandle,
    RemoteBaseUpdate,
    RemoteBaseUpdateOperation,
    RemoteBaseUpdateResult,
    RemoteFieldOptions,
    RemoteFieldSchema,
    RemoteFullDataOptions,
    RemoteHiddenMetadata,
    RemoteHiddenMetadataKey,
    RemoteHiddenMetadataType,
    RemoteLinkedRecordRef,
    RemoteReadFormat,
    RemoteReadOptions,
    RemoteRecord,
    RemoteRecordFieldData,
    RemoteTable,
    RemoteTableRegistry,
    RemoteTableSchema,
    RemoteViewSchema,
    UpdateRecordInput,
    UpsertInput,
    UpsertOptions,
    UpsertResult,
} from './lib/types.ts';

export { remoteBase as default } from './lib/class.ts';
