ROUND(
  LEN(
    REGEX_REPLACE(
      {Body},
      "(\\b|\\W)*(?P<T>(\\p{L}*[\\p{L}-]*([']\\p{L}+)?)*(?P<D>\\d+([.,]\\d+){0,2}\\w*)*)*\\s*|(\\p{P})+",
      '$<T>'
    )
  )
  / 
  LEN(
    REGEX_REPLACE(
      REGEX_REPLACE(
        TRIM({Body}),
        "(\\b|\\W)*(?P<T>(\\p{L}*[\\p{L}-]*([']\\p{L}+)?)*(?P<D>\\d+([.,]\\d+){0,2}\\w*)*)*\\s*|(\\p{P})+",
        '\n$<T>'
      ),
      '^\\s+|\\s+$|([^\n])[^\n]*\n?',
      '$1'
    )
  ),2
)
