REGEX_REPLACE(
  REGEX_REPLACE(
    REGEX_REPLACE(
      REGEX_REPLACE(
        REGEX_REPLACE(
          REGEX_REPLACE(
            REGEX_REPLACE(
              REGEX_REPLACE(
                REGEX_REPLACE(
                  REGEX_REPLACE(
                    REGEX_REPLACE(
                      REGEX_REPLACE(
                        REGEX_REPLACE(
                          REGEX_REPLACE(
                            REGEX_REPLACE(
                              REGEX_REPLACE(
                                Source,
                                '^\\s+|(^\\s*(([/][*](?s).*?[*][/])\\s*)+|([/]{2}.*\\s*))+|(((?P<str>(\\x22([^\\x22\n\\x5c]*(\\x5c\\x22)*)*\\x22)|(\\x27([^\\x27\n\\x5c]*(\\x5c\\x27)*)*\\x27)|(\\x60([^\\x60\\x5c]*(\\x5c\\x60)*)*\\x60))))|(\\s*(?P<end_of_args>[)]|\\s*(=>)\\s*)\\s+(?P<start_of_body>\\{))|((?P<space>\\x20)\\x20+)|((?P<newline>\n)+)|(([/][*](?s).*?[*][/]\\s*)|([/]{2}.*))([\\s;]*$)?|[;\\s]+$',
                                '$<end_of_args>$<start_of_body>$<space>$<newline>'
                                ),
                                '(?:(?m)^\\s*(?<ALL_EXPORT_STATEMENTS>export(?<a>(?<destructuringExport>\\s*{[^}]+})|\\s+default(?<exxKey>class|(async\\s+)?function)|.*))$|.+\\x0a*)+?',
                              '$<ALL_EXPORT_STATEMENTS>'
                            ),
                            '(\\w+|[*])\\s+as\\s+(?<renamed>\\w+)(,?\\s*)?|(?<fnRef>\\w+)\\s*\\((?s)[^(\\x0a]*(\\)(\\{[^}\\x0a]*\\}?)?),\\s*',
                            '$<renamed>\n'
                          ),
                          '^[\\s;]+|[;\\s]+$|(\n){1,}',
                          '$1'
                        ),
                        '(?m)^\\s+|\\s+$|(?m)^\\s*(?<ex>export)\\s*(?<ex_0>[{])\\s*(?<exDes>[^}]*)\\s*(?<ex_1>[}])|(?m)^export\\s+(?<deff>default)\\s+(async\\s+function|function|const|var|let|[\\[][^]]*\\]|\\{[^}]*\\}|\\d+|(?P<string>(\\x22([^\\x22\\n\\x5c]|\\x5c)*\\x22)|(\\x27([^\\x27\\n\\x5c]|\\x5c.)*\\x27)|(\\x60([^\\x60\\x5c]|\\x5c.)*\\x60)))|(?m)^export\\s+(async\\s+)?function\\s+(?<rrr>\\w+)\\b((\\s*\\(|\\s+\\w+\\s*\\()[^)]*\\)(\\s*\\{|\\s+\\w+\\s*\\{)[^}]*\\}).*?$',
                        '$<ex>$<ex_0>$<exDes>$<ex_1>$<deff>$<rrr>'
                      ),
                      '(?m)^export\\b(((?<defaultRef>default\\b)(\\s*\\{[^}]*\\}|\\s+((?:(class|const|let|var|(async\\s+)?function)\\b).*$(?<n00>\\x0a)*\\s*|(?<nl0>\\x0a)*\\s*|(?<fnKeyword>(async\\s+)?function\\s+)(?<fnRef>\\w+)|\\{(?<nestedRefs>.+)\\})|[\\x0a\\x09\\x20]+))|((?:(class|const|let|var|(async\\s+)?function)\\x20+(?<ref_1>[_\\w$]+).*|(?<fnKeyword_1>(async\\s+)?function\\s+)(?<fnRef_1>\\w+)|\\{(?<nestedRefs_1>.+)\\})|(?<nl>\\x0a)+\\s*|[\\x0a\\x09\\x20]+)){1,}',
                      '$<nl0>$<nl>$<ref_1>$<renamedRef>$<defaultRef>$<nl00>$<nl0>$<fnRef>$<fnRef_1>$<nestedRefs>$<nestedRefs_1>\n'
                    ),
                    '^\\s+|\\s+$|\\s*[;]?\\s*(\n)+',
                    '$1'
                  ),
                  '(?mU)^(((?:export\\s*\\{\\s*)\\b(?<du>.*)$|(?:\\s*(?<de>default)\\b.*$)))|(?:\\xa0+[;}]+)',
                  '$<de>$<du>'
                ),
                "(?m)^(?:export\\s+(?:async\\s+)?function\\s+(?<fRef_0>[\\pL_$][\\pL\\w_$]*)\\b(?:\\s*\\((?s)[^)]*\\)*\\))?)",
                "$<fRef_0>"
              ),
              "^\\s+|(?m)^(export\\s+)?function\\b\\s+|(?:(?:export\\s+(?:(?:async\\s+)?function))\\s+(?<reule>\\w+)\\s*\\((?s)[^\\)]*\\))",
              "$<reule>"
            ),
            '(^export\\b|(?m)^export\\b)\\s+(?:((async\\s+)?function\\s+(?<ref_okie_dokie>[\\pL_$][\\pL_\\w$]*))\\b(?:\\([^)\\x0a]*\\)?\\s*)?)(?:\\{[^}\\x0a]*\\}?)',
            '$<ref_okie_dokie>'
          ),
          "(?mU)^export\\s+",
          ""
        ),
        "(?m)^(async\\W)?function\\W(?<RERE_FN>\\w+)\\b.*",
        "$<RERE_FN>"
      ),
      '(?:(?m)^(\\b(?<kc0>[\\pL_$][\\pL\\w_$]*)\\s*,\\s*(?<kc1>[\\pL_$][\\pL\\w_$]*)\\b\\s*[;]?\\s*))|((?m)(?:^(?P<dede>default)\\b.+$)|export\\s*(\\W+((?:((async\\W+)?function\\W+)|(^((async\\W+)?function\\b\\s*(?<fnStart>[_\\pL$][_$\\pL\\w]*)\\b))|(?:(const|class|let|var)\\b\\s+))\\s*(?P<de>[\\pL_$][\\pL\\w_$]*).*$))|export\\s*{\\s*(?P<keep>.+)\\x0a+)|(?:[;]|[\\}]|\\s+){2,3}$',
      '$<dede>\n$<fnStart>\n$<de>$<kc0>\n$<kc1>\n$<keep>\n$<lineDown>'
    ),
    '^\n+|\n+$|\\s*[;]?\\s*(\n)+',
    '$1'
  ),
  "((?m)^(const|let|var|((async\\s+)?function)|class)\\b)\\W*(?<allRefs>\\w+)([=]|\\W+){2,}.*?$",
  '$<allRefs>'
)
